apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: vms-cnv-installation-policy
  namespace: vm-service-broker
  labels:
    app.kubernetes.io/component: acm-policy
    app.kubernetes.io/name: vm-service-broker
    app.kubernetes.io/part-of: vm-service-broker
spec:
  copyPolicyMetadata: false
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cnv-installation
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            # Create openshift-cnv Namespace
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-cnv
            # Create OperatorGroup for CNV
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: openshift-cnv
                  namespace: openshift-cnv
                spec:
                  targetNamespaces:
                  - openshift-cnv
            # Create Subscription for kubevirt-hyperconverged operator
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: kubevirt-hyperconverged
                  namespace: openshift-cnv
                spec:
                  channel: "stable"
                  name: kubevirt-hyperconverged
                  source: mirror-redhat-operators
                  sourceNamespace: openshift-marketplace
            # Create HyperConverged instance
            - complianceType: musthave
              objectDefinition:
                apiVersion: hco.kubevirt.io/v1beta1
                kind: HyperConverged
                metadata:
                  name: kubevirt-hyperconverged
                  namespace: openshift-cnv
                spec:
                  enableCommonBootImageImport: false
                  infra: {}
                  workloads: {}
            # Create openshift-virtualization-os-images Namespace
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-virtualization-os-images
            # Create DataImportCron for Fedora image
            - complianceType: musthave
              objectDefinition:
                apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataImportCron
                metadata:
                  name: fedora-image-cron-custom
                  namespace: openshift-virtualization-os-images
                spec:
                  garbageCollect: Outdated
                  managedDataSource: fedora-custom
                  schedule: "*/5 * * * *"
                  template:
                    metadata: {}
                    spec:
                      source:
                        registry:
                          pullMethod: node
                          url: 'docker://{{ .Values.sharedCluster.vmImageRepo }}{{ .Values.sharedCluster.vmSampleImage }}'
                      storage:
                        resources:
                          requests:
                            storage: 30Gi
                    status: {}
  remediationAction: enforce

# Made with Bob
