apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: vms-provisioning-binding
  namespace: vm-service-broker
placementRef:
  name: vms-provisioning-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: vms-cnv-installation-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
  - name: vms-cnv-rbac-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
  - name: vms-ns-provisioning-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io