apiVersion: v1
kind: Namespace
metadata:
  name: '{{ .Values.namespace }}'
  labels:
    app: '{{ .Values.application }}'
    by-squad: '{{ .Values.bySquadLabel }}'
    for-product: '{{ .Values.forProductLabel }}'
  annotations:
    argocd.argoproj.io/sync-wave: '-1'

# Made with Bob
