apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.application }}-deployment'
  namespace: {{ .Values.namespace }}
  labels:
    app: '{{ .Values.application }}'
    by-squad: '{{ .Values.bySquadLabel }}'
    for-product: '{{ .Values.forProductLabel }}'
    version: '{{ .Values.version }}'
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  selector:
    matchLabels:
      app: '{{ .Values.application }}'
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        group: {{ .Values.application }}
        app: {{ .Values.application }}
        version: {{ .Values.version }}
    spec:
      serviceAccountName: '{{ .Values.application }}-service-account'
      automountServiceAccountToken: true
      containers:
        - name: '{{ .Values.application }}-container'
          image: '{{ .Values.registry.imagesRepo }}{{ .Values.image }}'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.port }}
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.port }}
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: https
              containerPort: {{ .Values.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: '{{ .Values.application }}-config-map'
          env:
            - name: TLS_CERT
              value: /etc/tls/tls.crt
            - name: TLS_KEY
              value: /etc/tls/tls.key
            - name: CLIENT_CA
              value: /etc/mtls
          resources:
            requests:
              cpu: 25m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 200Mi
          
          volumeMounts:
            - name: tls-certificates
              mountPath: /etc/tls
              readOnly: true
            {{- if .Values.mtls.enabled }}
            - name: mtls-client-certs
              mountPath: /etc/mtls
              readOnly: true
            {{- end }}
            - name: ca-certificates
              mountPath: /etc/pki/tls/certs
              readOnly: true
      volumes:
        - name: tls-certificates
          secret:
            secretName: '{{ .Values.application }}-server-cert-secret'
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        {{- if .Values.mtls.enabled }}
        - name: mtls-client-certs
          secret:
            secretName: '{{ .Values.application }}-mtls-secret'
            items:
              - key: ca.crt
                path: ca.crt
        {{- end }}
        - name: ca-certificates
          secret:
            secretName: '{{ .Values.application }}-server-cert-secret'
            items:
              - key: ca.crt
                path: ca.crt
      
      terminationGracePeriodSeconds: 10