apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.application }}-service-account'
  namespace: '{{ .Values.namespace }}'
  labels:
    app: '{{ .Values.application }}'
    by-squad: '{{ .Values.bySquadLabel }}'
    for-product: '{{ .Values.forProductLabel }}'
  annotations:
    argocd.argoproj.io/sync-wave: '10'
imagePullSecrets:
  - name: '{{ .Values.application }}-pull-secret'
