apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Values.application }}-cluster-role'
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: '{{ .Values.application }}'
    by-squad: '{{ .Values.bySquadLabel }}'
    for-product: '{{ .Values.forProductLabel }}'
rules:
  - apiGroups: ["sovereign.cloud.ibm.com"]
    resources: ["vmnamespacerequests"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]