#!/bin/bash
set -e

# Script to apply SSO configuration to OpenShift cluster
# This script applies the Secret, ConfigMap, and OAuth patch generated by configure-sso.sh
# Usage: ./configure-vm-oauth.sh

# File names generated by configure-sso.sh
SECRET_FILE="openid-client-secret-vm-service.yaml"
CONFIGMAP_FILE="openid-ca-vm-service.yaml"
OAUTH_PATCH_FILE="oauth-cluster-patch.json"

echo "=========================================="
echo "Applying SSO Configuration to Cluster"
echo "=========================================="
echo ""

# Check if all required files exist
echo "Checking for required files..."
MISSING_FILES=0

if [ ! -f "$SECRET_FILE" ]; then
  echo "Error: $SECRET_FILE not found"
  MISSING_FILES=1
fi

if [ ! -f "$CONFIGMAP_FILE" ]; then
  echo "Error: $CONFIGMAP_FILE not found"
  MISSING_FILES=1
fi

if [ ! -f "$OAUTH_PATCH_FILE" ]; then
  echo "Error: $OAUTH_PATCH_FILE not found"
  MISSING_FILES=1
fi

if [ $MISSING_FILES -eq 1 ]; then
  echo ""
  echo "Please run configure-sso.sh first to generate the required files."
  exit 1
fi

echo "All required files found."
echo ""

# Apply the Secret
echo "Applying OpenID client secret..."
oc apply -f "$SECRET_FILE"
echo "✓ Secret applied successfully"
echo ""

# Apply the ConfigMap
echo "Applying OpenID CA ConfigMap..."
oc apply -f "$CONFIGMAP_FILE"
echo "✓ ConfigMap applied successfully"
echo ""

# Patch the OAuth resource
echo "Patching OAuth cluster resource..."

# Check if identityProviders array exists
if oc get oauth cluster -o jsonpath='{.spec.identityProviders}' 2>/dev/null | grep -q '\['; then
  # Array exists, append to it
  echo "Adding identity provider to existing list..."
  oc patch oauth cluster --type json --patch-file "$OAUTH_PATCH_FILE"
else
  # Array doesn't exist, create it with the first provider
  echo "Creating identityProviders array with new provider..."
  
  # Extract the identity provider configuration from the JSON patch file
  # The patch file contains a JSON array with an "add" operation, we need to extract the "value" field
  IDENTITY_PROVIDER=$(jq -r '.[0].value' "$OAUTH_PATCH_FILE")
  
  # Create the merge patch with the extracted identity provider
  MERGE_PATCH=$(jq -n --argjson provider "$IDENTITY_PROVIDER" '{
    "spec": {
      "identityProviders": [$provider]
    }
  }')
  
  oc patch oauth cluster --type merge --patch "$MERGE_PATCH"
fi

echo "✓ OAuth configuration applied successfully"
echo ""

echo "=========================================="
echo "Configuration Applied Successfully!"
echo "=========================================="
echo ""
echo "The OpenShift OAuth pods will restart automatically to apply the new configuration."
echo ""
echo "You can monitor the OAuth pod restart with:"
echo "  oc get pods -n openshift-authentication -w"
echo ""
echo "Once the pods are ready, users can authenticate using the new SSO provider."

# Made with Bob
